spring:
  application:
    name: mcp-location

server:
  port: 8084

weather:
  api-key: ${WEATHER_API_KEY:Enter_Your_Weather_Key_Here}

logging:
  level:
    root: INFO
    com.oneforth.mcplocation: DEBUG
